import { handleApiError } from "@/lib/error-handler";
import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

import { prisma } from "@/lib/prisma";

export async function POST(req: NextRequest) {
    const session = await getServerSession(authOptions);
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const settings = await prisma.siteSettings.findFirst();
    // @ts-ignore - IDE cache issue
    const STABILITY_API_KEY = settings?.stabilityApiKey || process.env.STABILITY_API_KEY;
    // @ts-ignore
    const imageAiProvider = settings?.imageAiProvider || "pollinations";

    try {
        const formData = await req.formData();
        const prompt = formData.get('prompt') as string;
        const imageFile = formData.get('image') as File | null;

        if (!prompt) {
            return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
        }

        // --- IMAGE-TO-IMAGE: Requires Paid API (Stability AI) ---
        if (imageFile) {
            if (!STABILITY_API_KEY) {
                return NextResponse.json({ error: "خاصية التعديل على الصور (Image-to-Image) تتطلب مفتاح Stability AI في الإعدادات." }, { status: 400 });
            }

            const endpoint = "https://api.stability.ai/v2beta/stable-image/generate/image-to-image";
            const bodyFormData = new FormData();
            bodyFormData.append("prompt", prompt);
            bodyFormData.append("output_format", "jpeg");
            bodyFormData.append("image", imageFile);
            bodyFormData.append("strength", "0.65"); 

            const response = await fetch(endpoint, {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${STABILITY_API_KEY}`,
                    Accept: "image/*"
                },
                body: bodyFormData,
            });

            if (!response.ok) {
                const errorData = await response.text();
                console.error("Stability Error:", errorData);
                return NextResponse.json({ error: "فشل توليد الصورة من Stability AI. يرجى التأكد من وجود رصيد كافٍ في حسابك." }, { status: response.status });
            }

            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            const base64 = buffer.toString('base64');
            const mimeType = response.headers.get("content-type") || 'image/jpeg';
            
            return NextResponse.json({ url: `data:${mimeType};base64,${base64}` });
        }

        // --- TEXT-TO-IMAGE Routing ---
        
        // 1. Imagen 3 (Requires Paid Google Account)
        if (imageAiProvider === "imagen") {
            // @ts-ignore
            const GEMINI_KEY = settings?.geminiApiKey || process.env.GEMINI_API_KEY;
            if (!GEMINI_KEY) {
                return NextResponse.json({ error: "مفتاح Gemini API غير متوفر. يرجى إضافته في الإعدادات." }, { status: 400 });
            }
            
            // Note: This endpoint will return 400 "only available on paid plans" for free tier accounts
            const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${GEMINI_KEY}`;
            const res = await fetch(url, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    instances: [{ prompt: prompt }],
                    parameters: { sampleCount: 1 }
                })
            });

            if (!res.ok) {
                const errData = await res.json();
                console.error("Imagen 3 Error:", errData);
                return NextResponse.json({ error: errData.error?.message || "فشل التوليد من Imagen 3. تأكد أن حسابك مدفوع." }, { status: res.status });
            }

            const data = await res.json();
            if (data.predictions && data.predictions[0]) {
                const base64 = data.predictions[0].bytesBase64Encoded;
                const mimeType = data.predictions[0].mimeType || 'image/jpeg';
                return NextResponse.json({ url: `data:${mimeType};base64,${base64}` });
            } else {
                return NextResponse.json({ error: "No image generated by Imagen" }, { status: 500 });
            }
        }
        
        // 2. Stability AI Core Text-to-Image
        else if (imageAiProvider === "stability") {
            if (!STABILITY_API_KEY) {
                return NextResponse.json({ error: "مفتاح Stability AI غير متوفر. يرجى إضافته في الإعدادات." }, { status: 400 });
            }

            const endpoint = "https://api.stability.ai/v2beta/stable-image/generate/core";
            const bodyFormData = new FormData();
            bodyFormData.append("prompt", prompt);
            bodyFormData.append("output_format", "jpeg");

            const response = await fetch(endpoint, {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${STABILITY_API_KEY}`,
                    Accept: "image/*"
                },
                body: bodyFormData,
            });

            if (!response.ok) {
                const errorData = await response.text();
                console.error("Stability Error:", errorData);
                return NextResponse.json({ error: "فشل توليد الصورة من Stability AI. تأكد من وجود رصيد كافٍ." }, { status: response.status });
            }

            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            const base64 = buffer.toString('base64');
            const mimeType = response.headers.get("content-type") || 'image/jpeg';
            
            return NextResponse.json({ url: `data:${mimeType};base64,${base64}` });
        }
        
        // 3. Pollinations AI (Default Free Fallback)
        else {
            const encodedPrompt = encodeURIComponent(prompt);
            const randomSeed = Math.floor(Math.random() * 1000000);
            const pollinationsUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=1024&height=1024&nologo=true&seed=${randomSeed}`;
            
            const response = await fetch(pollinationsUrl);
            
            if (!response.ok) {
                return NextResponse.json({ error: "فشل توليد الصورة من السيرفر المجاني (Pollinations)." }, { status: response.status });
            }

            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            const base64 = buffer.toString('base64');
            const mimeType = response.headers.get("content-type") || 'image/jpeg';
            
            return NextResponse.json({ url: `data:${mimeType};base64,${base64}` });
        }

    } catch (error: any) {
        console.error("AI Image Error:", error);
        return handleApiError(error);
    }
}
